from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import pandas as pd

_ROOT = Path(__file__).resolve().parents[1]
_SRC = _ROOT / "src"
if str(_SRC) not in sys.path:
    sys.path.insert(0, str(_SRC))


SELECTIONS = ["0", "1", "2", "3", "4", "5", "6", "7_plus"]


def _risk_tier(probability: float, expected_value: float) -> str:
    if expected_value <= 0:
        return "watch"
    if probability >= 0.25:
        return "single_candidate"
    if probability >= 0.16:
        return "small_stake_candidate"
    return "longshot_only"


def build_candidates(predictions: pd.DataFrame) -> pd.DataFrame:
    rows: list[dict[str, object]] = []
    for _, match in predictions.fillna("").iterrows():
        if int(float(match.get("sporttery_total_goals_odds_count", 0) or 0)) <= 0:
            continue
        for selection in SELECTIONS:
            probability_column = f"sporttery_total_goals_{selection}_probability"
            odds_column = f"sporttery_total_goals_{selection}_odds"
            market_column = f"sporttery_total_goals_{selection}_market_probability"
            edge_column = f"sporttery_total_goals_{selection}_edge"
            ev_column = f"sporttery_total_goals_{selection}_expected_value"
            if odds_column not in predictions.columns:
                continue
            odds = match.get(odds_column, "")
            expected_value = match.get(ev_column, "")
            if odds == "" or expected_value == "":
                continue
            probability = float(match.get(probability_column, 0.0) or 0.0)
            expected_value = float(expected_value)
            rows.append(
                {
                    "date": match.get("date", ""),
                    "match_id": match.get("match_id", ""),
                    "home_team": match.get("home_team", ""),
                    "away_team": match.get("away_team", ""),
                    "selection": selection,
                    "model_probability": probability,
                    "odds": float(odds),
                    "market_probability": float(match.get(market_column, 0.0) or 0.0),
                    "edge": float(match.get(edge_column, 0.0) or 0.0),
                    "expected_value": expected_value,
                    "risk_tier": _risk_tier(probability, expected_value),
                    "model_double_pick": match.get(
                        "sporttery_total_goals_double_pick",
                        "",
                    ),
                    "top_score_1": match.get("top_score_1", ""),
                    "top_score_2": match.get("top_score_2", ""),
                    "under_2_5_probability": match.get("under_2_5_probability", ""),
                    "over_2_5_probability": match.get("over_2_5_probability", ""),
                }
            )
    candidates = pd.DataFrame(rows)
    if candidates.empty:
        return candidates
    return candidates.sort_values(
        ["expected_value", "edge", "model_probability"],
        ascending=[False, False, False],
    ).reset_index(drop=True)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--predictions",
        required=True,
        help="Prediction CSV generated by run_world_cup_lineup_adjusted.py.",
    )
    parser.add_argument(
        "--output",
        default="artifacts/predictions/sporttery_total_goals_candidates.csv",
    )
    parser.add_argument(
        "--audit-output",
        default="artifacts/predictions/sporttery_total_goals_candidates.json",
    )
    args = parser.parse_args()

    predictions_path = _ROOT / args.predictions
    predictions = pd.read_csv(predictions_path)
    candidates = build_candidates(predictions)

    output_path = _ROOT / args.output
    output_path.parent.mkdir(parents=True, exist_ok=True)
    candidates.to_csv(output_path, index=False)

    audit = {
        "predictions": str(predictions_path),
        "prediction_matches": int(len(predictions)),
        "candidate_rows": int(len(candidates)),
        "positive_ev_rows": int(candidates["expected_value"].gt(0).sum())
        if not candidates.empty
        else 0,
        "single_candidates": int(candidates["risk_tier"].eq("single_candidate").sum())
        if not candidates.empty
        else 0,
        "output": str(output_path),
    }
    audit_path = _ROOT / args.audit_output
    audit_path.parent.mkdir(parents=True, exist_ok=True)
    audit_path.write_text(json.dumps(audit, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(audit, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
