from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import pandas as pd
import numpy as np

_ROOT = Path(__file__).resolve().parents[1]
_SRC = _ROOT / "src"
if str(_SRC) not in sys.path:
    sys.path.insert(0, str(_SRC))

from world_cup.data import load_international_results
from world_cup.data import normalize_national_team
from world_cup.data_completeness import data_completeness_summary
from world_cup.lineup_adjustment import build_fixture_lineup_adjustments
from world_cup.markets import market_edge_analysis
from world_cup.markets import summarize_score_markets
from world_cup.model import WorldCupBaselineModel
from world_cup.knockout import empty_knockout_adjustment
from world_cup.knockout import is_knockout_stage
from world_cup.knockout import knockout_adjustment
from world_cup.knockout_market_calibration import knockout_market_calibration
from world_cup.player_data import load_player_data_bundle
from world_cup.realtime_sources import absence_goal_shift
from world_cup.realtime_sources import find_line_movement
from world_cup.realtime_sources import find_realtime_lineup
from world_cup.realtime_sources import find_team_absences
from world_cup.realtime_sources import load_absence_index
from world_cup.realtime_sources import load_line_movement_index
from world_cup.realtime_sources import load_realtime_lineup_index
from world_cup.realtime_sources import load_structured_intelligence_index
from world_cup.sporttery_markets import find_sporttery_market
from world_cup.sporttery_markets import index_sporttery_markets
from world_cup.sporttery_markets import load_sporttery_handicap_markets
from world_cup.sporttery_play_odds import find_play_odds
from world_cup.sporttery_play_odds import flatten_play_market_value
from world_cup.sporttery_play_odds import load_sporttery_play_odds
from world_cup.sporttery_play_odds import play_market_value
from world_cup.sporttery_play_odds import total_goals_model_probabilities
from world_cup.the_odds_api_adapter import find_the_odds_api_h2h
from world_cup.the_odds_api_adapter import index_the_odds_api_h2h
from world_cup.the_odds_api_adapter import load_the_odds_api_summary


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--international-results",
        default="data/external/international-results/results.csv",
    )
    parser.add_argument(
        "--player-data-dir",
        default="data/player_level/espn_world_cup_2026",
    )
    parser.add_argument(
        "--fixtures",
        default="data/player_level/espn_world_cup_2026/fixtures.csv",
    )
    parser.add_argument(
        "--player-strengths",
        default="data/player_level/espn_world_cup_2026/player_strengths.csv",
    )
    parser.add_argument(
        "--leisu-features",
        default="",
        help="Optional Leisu public fixture features CSV generated by build_leisu_world_cup_features.py.",
    )
    parser.add_argument(
        "--sporttery-markets",
        default="",
        help="Optional China Sports Lottery handicap market CSV. Uses official handicap lines when present.",
    )
    parser.add_argument(
        "--sporttery-play-odds",
        default="",
        help="Optional China Sports Lottery play odds CSV for total goals, correct score, half/full-time, etc.",
    )
    parser.add_argument("--line-movement", default="")
    parser.add_argument(
        "--the-odds-api-summary",
        default="",
        help="Optional The Odds API match_market_summary.csv for multi-bookmaker market comparison.",
    )
    parser.add_argument("--structured-intelligence", default="")
    parser.add_argument("--absences", default="")
    parser.add_argument("--realtime-lineups", default="")
    parser.add_argument("--as-of-date", required=True)
    parser.add_argument("--draw-correlation", type=float, default=0.0)
    parser.add_argument(
        "--output",
        default="artifacts/predictions/world_cup_lineup_adjusted.csv",
    )
    parser.add_argument(
        "--audit-output",
        default="artifacts/predictions/world_cup_lineup_adjusted.json",
    )
    args = parser.parse_args()

    as_of_date = pd.Timestamp(args.as_of_date).normalize()
    matches = load_international_results(_ROOT / args.international_results)
    training = matches[matches["date"].lt(as_of_date)]
    model = WorldCupBaselineModel(draw_correlation=args.draw_correlation).fit(training)

    bundle = load_player_data_bundle(_ROOT / args.player_data_dir)
    fixtures = pd.read_csv(_ROOT / args.fixtures)
    fixtures["date"] = pd.to_datetime(fixtures["date"], errors="raise")
    leisu_by_match_id: dict[str, dict[str, object]] = {}
    if args.leisu_features:
        leisu_features_path = _ROOT / args.leisu_features
        if leisu_features_path.exists():
            leisu_features = pd.read_csv(
                leisu_features_path,
                dtype={"match_id": str, "leisu_match_id": str},
            )
            if "match_id" in leisu_features.columns:
                leisu_by_match_id = {
                    str(row["match_id"]): row.to_dict()
                    for _, row in leisu_features.iterrows()
                }
    sporttery_by_fixture: dict[tuple[str, str, str], dict[str, object]] = {}
    sporttery_path_exists = False
    if args.sporttery_markets:
        sporttery_path = _ROOT / args.sporttery_markets
        sporttery_path_exists = sporttery_path.exists()
        if sporttery_path.exists():
            sporttery_by_fixture = index_sporttery_markets(
                load_sporttery_handicap_markets(sporttery_path)
            )
    sporttery_play_odds = pd.DataFrame()
    sporttery_play_odds_path_exists = False
    if args.sporttery_play_odds:
        sporttery_play_odds_path = _ROOT / args.sporttery_play_odds
        sporttery_play_odds_path_exists = sporttery_play_odds_path.exists()
        if sporttery_play_odds_path.exists():
            sporttery_play_odds = load_sporttery_play_odds(sporttery_play_odds_path)
    line_movement_by_fixture = load_line_movement_index(_ROOT / args.line_movement if args.line_movement else None)
    the_odds_api_summary = load_the_odds_api_summary(
        _ROOT / args.the_odds_api_summary if args.the_odds_api_summary else None
    )
    the_odds_api_h2h = index_the_odds_api_h2h(the_odds_api_summary)
    structured_intelligence_by_match_id = load_structured_intelligence_index(
        _ROOT / args.structured_intelligence if args.structured_intelligence else None
    )
    absence_by_team = load_absence_index(_ROOT / args.absences if args.absences else None)
    realtime_lineup_by_team = load_realtime_lineup_index(
        _ROOT / args.realtime_lineups if args.realtime_lineups else None
    )
    known_teams = set(bundle.squads["team"].map(normalize_national_team))
    upcoming_all = fixtures[fixtures["date"].ge(as_of_date)].copy()
    upcoming = upcoming_all[
        upcoming_all["home_team"].map(normalize_national_team).isin(known_teams)
        & upcoming_all["away_team"].map(normalize_national_team).isin(known_teams)
    ].copy()
    if upcoming.empty:
        raise SystemExit(f"no fixtures found on or after {as_of_date.date()}")

    strength_path = _ROOT / args.player_strengths
    player_strengths = (
        pd.read_csv(strength_path)
        if strength_path.exists()
        else pd.DataFrame()
    )
    adjustments = build_fixture_lineup_adjustments(
        bundle,
        upcoming,
        player_strengths=player_strengths,
    )
    rows = []
    for fixture, adjustment in zip(upcoming.itertuples(index=False), adjustments.itertuples(index=False)):
        base = model.predict_match(
            fixture.home_team,
            fixture.away_team,
            neutral=True,
        )
        home_absences = find_team_absences(
            absence_by_team,
            date=fixture.date,
            team=fixture.home_team,
        )
        away_absences = find_team_absences(
            absence_by_team,
            date=fixture.date,
            team=fixture.away_team,
        )
        injury_shift = absence_goal_shift(home_absences, away_absences)
        home_multiplier = float(adjustment.home_goal_multiplier) * float(np.exp(injury_shift))
        away_multiplier = float(adjustment.away_goal_multiplier) * float(np.exp(-injury_shift))
        adjusted = model.predict_match(
            fixture.home_team,
            fixture.away_team,
            neutral=True,
            home_goal_multiplier=home_multiplier,
            away_goal_multiplier=away_multiplier,
        )
        sporttery_market = find_sporttery_market(
            sporttery_by_fixture,
            date=fixture.date,
            home_team=fixture.home_team,
            away_team=fixture.away_team,
        )
        official_home_handicap = (
            float(sporttery_market["home_handicap"])
            if sporttery_market is not None
            else None
        )
        line_movement = find_line_movement(
            line_movement_by_fixture,
            date=fixture.date,
            home_team=fixture.home_team,
            away_team=fixture.away_team,
        )
        the_odds_api_market = find_the_odds_api_h2h(
            the_odds_api_h2h,
            date=fixture.date,
            home_team=fixture.home_team,
            away_team=fixture.away_team,
        )
        structured_intelligence = structured_intelligence_by_match_id.get(
            str(fixture.match_id),
            {},
        )
        home_realtime_lineup = find_realtime_lineup(
            realtime_lineup_by_team,
            match_id=fixture.match_id,
            team=fixture.home_team,
        )
        away_realtime_lineup = find_realtime_lineup(
            realtime_lineup_by_team,
            match_id=fixture.match_id,
            team=fixture.away_team,
        )
        markets = summarize_score_markets(
            adjusted["score_matrix"],
            home_handicap=official_home_handicap,
            expected_home_goals=adjusted["expected_home_goals"],
            expected_away_goals=adjusted["expected_away_goals"],
        )
        handicap = markets["handicap"]
        total_goals = markets["total_goals"]
        total_goal_probabilities = total_goals["sporttery_total_goal_probabilities"]
        top_total_goals = total_goals["top_total_goal_selections"]
        sporttery_total_goals_odds = find_play_odds(
            sporttery_play_odds,
            date=fixture.date,
            home_team=fixture.home_team,
            away_team=fixture.away_team,
            play_type="total_goals",
        )
        total_goals_value = play_market_value(
            total_goals_model_probabilities(total_goals),
            sporttery_total_goals_odds,
        )
        total_goals_value_fields = flatten_play_market_value(
            total_goals_value,
            prefix="sporttery_total_goals",
            selections=["0", "1", "2", "3", "4", "5", "6", "7_plus"],
        )
        sporttery_correct_score_odds = find_play_odds(
            sporttery_play_odds,
            date=fixture.date,
            home_team=fixture.home_team,
            away_team=fixture.away_team,
            play_type="correct_score",
        )
        correct_score_value = play_market_value(
            markets["correct_score"],
            sporttery_correct_score_odds,
        )
        spf_edge = market_edge_analysis(
            {
                "home_win": adjusted["p_home"],
                "draw": adjusted["p_draw"],
                "away_win": adjusted["p_away"],
            },
            {
                "home_win": sporttery_market.get("spf_odds_home", "")
                if sporttery_market
                else "",
                "draw": sporttery_market.get("spf_odds_draw", "")
                if sporttery_market
                else "",
                "away_win": sporttery_market.get("spf_odds_away", "")
                if sporttery_market
                else "",
            },
        )
        handicap_edge = market_edge_analysis(
            {
                "handicap_home_win": handicap["handicap_home_win"],
                "handicap_draw": handicap["handicap_draw"],
                "handicap_away_win": handicap["handicap_away_win"],
            },
            {
                "handicap_home_win": sporttery_market.get("rqspf_odds_home", "")
                if sporttery_market
                else "",
                "handicap_draw": sporttery_market.get("rqspf_odds_draw", "")
                if sporttery_market
                else "",
                "handicap_away_win": sporttery_market.get("rqspf_odds_away", "")
                if sporttery_market
                else "",
            },
        )
        the_odds_api_edge = market_edge_analysis(
            {
                "home_win": adjusted["p_home"],
                "draw": adjusted["p_draw"],
                "away_win": adjusted["p_away"],
            },
            {
                "home_win": the_odds_api_market.get("home_avg_odds", ""),
                "draw": the_odds_api_market.get("draw_avg_odds", ""),
                "away_win": the_odds_api_market.get("away_avg_odds", ""),
            },
        )
        stage = str(getattr(fixture, "stage", "") or "")
        is_knockout = is_knockout_stage(stage)
        if is_knockout:
            knockout = knockout_adjustment(
                score_matrix=adjusted["score_matrix"],
                p_home=adjusted["p_home"],
                p_draw=adjusted["p_draw"],
                p_away=adjusted["p_away"],
                expected_home_goals=adjusted["expected_home_goals"],
                expected_away_goals=adjusted["expected_away_goals"],
                market_home_probability=the_odds_api_edge["market_probabilities"][
                    "home_win"
                ],
                market_draw_probability=the_odds_api_edge["market_probabilities"][
                    "draw"
                ],
                market_away_probability=the_odds_api_edge["market_probabilities"][
                    "away_win"
                ],
            )
        else:
            knockout = empty_knockout_adjustment()
        knockout_market = knockout_market_calibration(
            is_knockout=is_knockout,
            p_home=adjusted["p_home"],
            p_draw=adjusted["p_draw"],
            p_away=adjusted["p_away"],
            expected_home_goals=adjusted["expected_home_goals"],
            expected_away_goals=adjusted["expected_away_goals"],
            handicap_line=handicap["home_handicap"],
            handicap_home_win_probability=handicap["handicap_home_win"],
            handicap_draw_probability=handicap["handicap_draw"],
            handicap_away_win_probability=handicap["handicap_away_win"],
            under_2_5_probability=total_goals["under_2_5_probability"],
            over_2_5_probability=total_goals["over_2_5_probability"],
            knockout_extra_time_probability=knockout.get(
                "knockout_extra_time_probability"
            ),
            knockout_penalty_shootout_probability=knockout.get(
                "knockout_penalty_shootout_probability"
            ),
        )
        row = {
            "date": str(pd.Timestamp(fixture.date).date()),
            "match_id": fixture.match_id,
            "stage": stage,
            "is_knockout": int(is_knockout),
            "home_team": fixture.home_team,
            "away_team": fixture.away_team,
            "lineup_adjustment_active": int(adjustment.lineup_adjustment_active),
            "home_lineup_confirmed": int(adjustment.home_lineup_confirmed),
            "away_lineup_confirmed": int(adjustment.away_lineup_confirmed),
            "lineup_strength_diff": adjustment.lineup_strength_diff,
            "lineup_relative_strength_diff": getattr(
                adjustment,
                "lineup_relative_strength_diff",
                0.0,
            ),
            "home_player_strength_confidence": getattr(
                adjustment,
                "home_player_strength_confidence",
                0.0,
            ),
            "away_player_strength_confidence": getattr(
                adjustment,
                "away_player_strength_confidence",
                0.0,
            ),
            "home_goal_multiplier": adjustment.home_goal_multiplier,
            "away_goal_multiplier": adjustment.away_goal_multiplier,
            "final_home_goal_multiplier": home_multiplier,
            "final_away_goal_multiplier": away_multiplier,
            "absence_goal_shift": injury_shift,
            "base_p_home": base["p_home"],
            "base_p_draw": base["p_draw"],
            "base_p_away": base["p_away"],
            "adjusted_p_home": adjusted["p_home"],
            "adjusted_p_draw": adjusted["p_draw"],
            "adjusted_p_away": adjusted["p_away"],
            "expected_home_goals": adjusted["expected_home_goals"],
            "expected_away_goals": adjusted["expected_away_goals"],
            "top_score_1": markets["top_scorelines"][0]["score"],
            "top_score_1_probability": markets["top_scorelines"][0]["probability"],
            "top_score_2": markets["top_scorelines"][1]["score"],
            "top_score_2_probability": markets["top_scorelines"][1]["probability"],
            "over_2_5_probability": total_goals["over_2_5_probability"],
            "under_2_5_probability": total_goals["under_2_5_probability"],
            "sporttery_total_goals_0_probability": total_goal_probabilities.get(
                "total_goals_0_probability",
                0.0,
            ),
            "sporttery_total_goals_1_probability": total_goal_probabilities.get(
                "total_goals_1_probability",
                0.0,
            ),
            "sporttery_total_goals_2_probability": total_goal_probabilities.get(
                "total_goals_2_probability",
                0.0,
            ),
            "sporttery_total_goals_3_probability": total_goal_probabilities.get(
                "total_goals_3_probability",
                0.0,
            ),
            "sporttery_total_goals_4_probability": total_goal_probabilities.get(
                "total_goals_4_probability",
                0.0,
            ),
            "sporttery_total_goals_5_probability": total_goal_probabilities.get(
                "total_goals_5_probability",
                0.0,
            ),
            "sporttery_total_goals_6_probability": total_goal_probabilities.get(
                "total_goals_6_probability",
                0.0,
            ),
            "sporttery_total_goals_7_plus_probability": total_goal_probabilities.get(
                "total_goals_7_plus_probability",
                0.0,
            ),
            "sporttery_total_goals_top_1": top_total_goals[0]["selection"],
            "sporttery_total_goals_top_1_probability": top_total_goals[0]["probability"],
            "sporttery_total_goals_top_2": top_total_goals[1]["selection"],
            "sporttery_total_goals_top_2_probability": top_total_goals[1]["probability"],
            "sporttery_total_goals_double_pick": (
                f'{top_total_goals[0]["selection"]}/{top_total_goals[1]["selection"]}'
            ),
            "sporttery_total_goals_odds_count": len(sporttery_total_goals_odds),
            **total_goals_value_fields,
            "sporttery_correct_score_odds_count": len(sporttery_correct_score_odds),
            "sporttery_correct_score_best_selection": correct_score_value.get(
                "best_selection",
                "",
            ),
            "sporttery_correct_score_best_expected_value": correct_score_value.get(
                "best_expected_value"
            ),
            "sporttery_correct_score_best_edge": correct_score_value.get("best_edge"),
            "sporttery_correct_score_value_signal": (
                "positive"
                if correct_score_value.get("best_expected_value") is not None
                and float(correct_score_value["best_expected_value"]) > 0
                else "watch"
                if correct_score_value.get("best_selection")
                else "no_market"
            ),
            "handicap_line": handicap["home_handicap"],
            "handicap_label": handicap["handicap_label"],
            "handicap_home_win_probability": handicap["handicap_home_win"],
            "handicap_draw_probability": handicap["handicap_draw"],
            "handicap_away_win_probability": handicap["handicap_away_win"],
            "handicap_recommended_key": handicap["recommended_key"],
            "handicap_recommended_result": handicap["recommended_result"],
            "handicap_recommended_probability": handicap["recommended_probability"],
            "handicap_line_source": "sporttery" if sporttery_market else "model_inferred",
            "sporttery_match_number": (
                str(sporttery_market.get("match_number", ""))
                if sporttery_market
                else ""
            ),
            "sporttery_market_source": (
                str(sporttery_market.get("source", ""))
                if sporttery_market
                else ""
            ),
            "sporttery_market_updated_at": (
                str(sporttery_market.get("updated_at", ""))
                if sporttery_market
                else ""
            ),
            "spf_market_home_probability": spf_edge["market_probabilities"]["home_win"],
            "spf_market_draw_probability": spf_edge["market_probabilities"]["draw"],
            "spf_market_away_probability": spf_edge["market_probabilities"]["away_win"],
            "spf_value_best_key": spf_edge["best_key"],
            "spf_value_best_result": spf_edge["best_label"],
            "spf_value_best_edge": spf_edge["best_edge"],
            "spf_value_best_expected_value": spf_edge["best_expected_value"],
            "spf_value_signal": spf_edge["signal"],
            "handicap_market_home_probability": handicap_edge["market_probabilities"][
                "handicap_home_win"
            ],
            "handicap_market_draw_probability": handicap_edge["market_probabilities"][
                "handicap_draw"
            ],
            "handicap_market_away_probability": handicap_edge["market_probabilities"][
                "handicap_away_win"
            ],
            "handicap_value_best_key": handicap_edge["best_key"],
            "handicap_value_best_result": handicap_edge["best_label"],
            "handicap_value_best_edge": handicap_edge["best_edge"],
            "handicap_value_best_expected_value": handicap_edge["best_expected_value"],
            "handicap_value_signal": handicap_edge["signal"],
            "the_odds_api_market_source": (
                str(the_odds_api_market.get("source", ""))
                if the_odds_api_market
                else ""
            ),
            "the_odds_api_event_id": (
                str(the_odds_api_market.get("event_id", ""))
                if the_odds_api_market
                else ""
            ),
            "multi_bookmaker_h2h_count": int(
                the_odds_api_market.get("bookmaker_count", 0) or 0
            ),
            "the_odds_api_home_avg_odds": the_odds_api_market.get("home_avg_odds", ""),
            "the_odds_api_draw_avg_odds": the_odds_api_market.get("draw_avg_odds", ""),
            "the_odds_api_away_avg_odds": the_odds_api_market.get("away_avg_odds", ""),
            "the_odds_api_home_best_odds": the_odds_api_market.get("home_best_odds", ""),
            "the_odds_api_draw_best_odds": the_odds_api_market.get("draw_best_odds", ""),
            "the_odds_api_away_best_odds": the_odds_api_market.get("away_best_odds", ""),
            "the_odds_api_market_home_probability": the_odds_api_edge["market_probabilities"]["home_win"],
            "the_odds_api_market_draw_probability": the_odds_api_edge["market_probabilities"]["draw"],
            "the_odds_api_market_away_probability": the_odds_api_edge["market_probabilities"]["away_win"],
            "the_odds_api_value_best_key": the_odds_api_edge["best_key"],
            "the_odds_api_value_best_result": the_odds_api_edge["best_label"],
            "the_odds_api_value_best_edge": the_odds_api_edge["best_edge"],
            "the_odds_api_value_best_expected_value": the_odds_api_edge["best_expected_value"],
            "the_odds_api_value_signal": the_odds_api_edge["signal"],
            **knockout,
            **knockout_market,
            "line_movement_opening_home_handicap": line_movement.get("opening_home_handicap", ""),
            "line_movement_latest_home_handicap": line_movement.get("latest_home_handicap", ""),
            "line_movement_delta": line_movement.get("handicap_line_delta", ""),
            "line_movement_direction": line_movement.get("handicap_movement_direction", ""),
            "line_movement_favorite_movement": line_movement.get("favorite_movement", ""),
            "line_movement_snapshots": line_movement.get("snapshots", ""),
            "home_absence_count": int(home_absences.get("absence_count", 0) or 0),
            "away_absence_count": int(away_absences.get("absence_count", 0) or 0),
            "home_absence_weighted_impact": float(home_absences.get("absence_weighted_impact", 0.0) or 0.0),
            "away_absence_weighted_impact": float(away_absences.get("absence_weighted_impact", 0.0) or 0.0),
            "home_injury_count": int(home_absences.get("injury_count", 0) or 0),
            "away_injury_count": int(away_absences.get("injury_count", 0) or 0),
            "home_suspension_count": int(home_absences.get("suspension_count", 0) or 0),
            "away_suspension_count": int(away_absences.get("suspension_count", 0) or 0),
            "structured_intelligence_count": int(structured_intelligence.get("structured_intelligence_count", 0) or 0),
            "structured_intelligence_severity": float(structured_intelligence.get("structured_intelligence_severity", 0.0) or 0.0),
            "structured_injury_count": int(structured_intelligence.get("structured_injury_count", 0) or 0),
            "structured_suspension_count": int(structured_intelligence.get("structured_suspension_count", 0) or 0),
            "structured_tactical_count": int(structured_intelligence.get("structured_tactical_count", 0) or 0),
            "structured_motivation_count": int(structured_intelligence.get("structured_motivation_count", 0) or 0),
            "structured_schedule_count": int(structured_intelligence.get("structured_schedule_count", 0) or 0),
            "home_realtime_lineup_confirmed": int(home_realtime_lineup.get("realtime_lineup_confirmed", 0) or 0),
            "away_realtime_lineup_confirmed": int(away_realtime_lineup.get("realtime_lineup_confirmed", 0) or 0),
            "home_realtime_starters": int(home_realtime_lineup.get("realtime_starters", 0) or 0),
            "away_realtime_starters": int(away_realtime_lineup.get("realtime_starters", 0) or 0),
            "home_realtime_substitutes": int(home_realtime_lineup.get("realtime_substitutes", 0) or 0),
            "away_realtime_substitutes": int(away_realtime_lineup.get("realtime_substitutes", 0) or 0),
        }
        leisu = leisu_by_match_id.get(str(fixture.match_id), {})
        row.update(
            {
                "leisu_public_match_linked": int(leisu.get("leisu_public_match_linked", 0) or 0),
                "leisu_match_id": str(leisu.get("leisu_match_id", "") or ""),
                "leisu_intelligence_count": int(leisu.get("leisu_intelligence_count", 0) or 0),
                "leisu_has_intelligence": int(leisu.get("leisu_has_intelligence", 0) or 0),
                "leisu_detail_url": str(leisu.get("leisu_detail_url", "") or ""),
                "leisu_intelligence_url": str(leisu.get("leisu_intelligence_url", "") or ""),
            }
        )
        row.update(data_completeness_summary(row))
        rows.append(row)

    output = pd.DataFrame(rows)
    output_path = _ROOT / args.output
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output.to_csv(output_path, index=False)
    sporttery_lines_used = int((output["handicap_line_source"] == "sporttery").sum())
    sporttery_coverage = sporttery_lines_used / len(output) if len(output) else 0.0
    if not args.sporttery_markets:
        sporttery_status = "not_configured"
    elif not sporttery_path_exists:
        sporttery_status = "missing_file"
    elif sporttery_lines_used == len(output):
        sporttery_status = "complete"
    elif sporttery_lines_used > 0:
        sporttery_status = "partial"
    else:
        sporttery_status = "empty"
    audit = {
        "as_of_date": str(as_of_date.date()),
        "fixtures": int(len(output)),
        "skipped_placeholder_fixtures": int(len(upcoming_all) - len(upcoming)),
        "lineup_adjustment_active_matches": int(output["lineup_adjustment_active"].sum()),
        "confirmed_home_lineups": int(output["home_lineup_confirmed"].sum()),
        "confirmed_away_lineups": int(output["away_lineup_confirmed"].sum()),
        "player_strengths_loaded": bool(not player_strengths.empty),
        "leisu_features_loaded": bool(leisu_by_match_id),
        "leisu_linked_predictions": int(output["leisu_public_match_linked"].sum()),
        "leisu_predictions_with_intelligence": int(output["leisu_has_intelligence"].sum()),
        "sporttery_markets_loaded": bool(sporttery_by_fixture),
        "sporttery_play_odds_loaded": bool(not sporttery_play_odds.empty),
        "line_movement_loaded": bool(line_movement_by_fixture),
        "the_odds_api_summary_loaded": bool(the_odds_api_h2h),
        "structured_intelligence_loaded": bool(structured_intelligence_by_match_id),
        "absences_loaded": bool(absence_by_team),
        "realtime_lineups_loaded": bool(realtime_lineup_by_team),
        "predictions_with_line_movement": int(pd.to_numeric(output.get("line_movement_snapshots", 0), errors="coerce").fillna(0).gt(0).sum()),
        "predictions_with_the_odds_api_h2h": int(pd.to_numeric(output.get("multi_bookmaker_h2h_count", 0), errors="coerce").fillna(0).gt(0).sum()),
        "predictions_with_structured_intelligence": int(output["structured_intelligence_count"].gt(0).sum()),
        "predictions_with_absences": int((output["home_absence_count"] + output["away_absence_count"]).gt(0).sum()),
        "predictions_with_realtime_lineups": int((output["home_realtime_lineup_confirmed"] + output["away_realtime_lineup_confirmed"]).gt(0).sum()),
        "knockout_predictions": int(output["is_knockout"].sum()),
        "knockout_predictions_with_market_divergence": int(
            output["knockout_market_divergence_signal"]
            .isin(["direction_conflict", "large_probability_gap", "watch_gap"])
            .sum()
        ),
        "knockout_high_draw_penalty_risk": int(
            output["knockout_risk_signal"].eq("high_draw_penalty_risk").sum()
        ),
        "sporttery_markets_path": args.sporttery_markets,
        "sporttery_markets_file_exists": sporttery_path_exists,
        "sporttery_play_odds_path": args.sporttery_play_odds,
        "sporttery_play_odds_file_exists": sporttery_play_odds_path_exists,
        "sporttery_play_odds_rows": int(len(sporttery_play_odds)),
        "sporttery_total_goals_odds_matches": int(
            output["sporttery_total_goals_odds_count"].gt(0).sum()
        ),
        "sporttery_correct_score_odds_matches": int(
            output["sporttery_correct_score_odds_count"].gt(0).sum()
        ),
        "sporttery_handicap_lines_used": sporttery_lines_used,
        "sporttery_handicap_coverage": sporttery_coverage,
        "sporttery_handicap_quality_status": sporttery_status,
        "mean_player_strength_confidence_in_predictions": float(
            output[
                ["home_player_strength_confidence", "away_player_strength_confidence"]
            ].mean().mean()
        ),
        "mean_data_completeness_score": float(output["data_completeness_score"].mean()),
        "data_completeness_grade_counts": {
            str(key): int(value)
            for key, value in output["data_completeness_grade"].value_counts().sort_index().items()
        },
        "output": str(output_path),
        "method": "conservative lineup adjustment; inactive unless both teams have confirmed 11-player lineups",
    }
    audit_path = _ROOT / args.audit_output
    audit_path.parent.mkdir(parents=True, exist_ok=True)
    audit_path.write_text(json.dumps(audit, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(audit, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
